version: "3.9"

services:

  mongo_db:
    image: mongo
    container_name: mongo_db
    env_file:
      - metabase/config/mongo_exemple.env
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo_db:/data/db
  
  postgres:
    image: postgres:alpine3.17
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - metabase/config/postgres_exemple.env
    restart: always
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    env_file:
      - metabase/config/metabase_database_exemple.env
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data/metabase:/data

networks:
  default:
    name: pynalytics